import Header from "@/components/custom/Header";
import { Button } from "@/components/ui/button";
import { ResumeInfoContext } from "@/context/ResumeInfoContext";
import ResumePreview from "@/dashboard/resume/components/ResumePreview";
import { Download, Share } from "lucide-react";
import React, { useEffect } from "react";
import { useParams } from "react-router-dom";
import { GetResumeById } from "../../../../services/GlobalApi";
import { RWebShare } from "react-web-share";

function ViewResume() {
  const [resumeInfo, setResumeInfo] = React.useState(null);
  const { resumeId } = useParams();
  const GetResumeInfo = () => {
    GetResumeById(resumeId).then((res) => {
      setResumeInfo(res?.data?.resumes);
    });
  };

  useEffect(() => {
    GetResumeInfo();
  }, [resumeId]);

  return (
    <ResumeInfoContext.Provider value={{ resumeInfo, setResumeInfo }}>
      <div id="no-print">
        <Header />
        <div className="my-10 mx-10 md:mx-20 lg:mx-40">
          <h2 className="text-center text-2xl font-medium">
            Congrats! your Ultimate AI generates Resume is ready !
          </h2>
          <p className="text-center text-gray-400">
            Now you are ready to download your resume and you can share your
            unique resume url with your friends and family
          </p>
          <div className="flex justify-between my-10 px-44">
            <Button onClick={() => window.print()}>
              <Download />
              Download
            </Button>
            <RWebShare
              data={{
                text: "Hi there! Check out my resume generated by AI. It's amazing!",
                title: `${resumeInfo?.firstName} ${resumeInfo?.lastName} Resume`,
                url: `/my-resume/${resumeId}/view`,
              }}
              onClick={() => console.log("shared successfully!")}
            >
              <Button>
                <Share />
                Share
              </Button>
            </RWebShare>
          </div>
        </div>
      </div>
      <div id="print-start" className="my-10 mx-10 md:mx-20 lg:mx-36">
        <div id="print-area">
          <ResumePreview />
        </div>
      </div>
    </ResumeInfoContext.Provider>
  );
}

export default ViewResume;
